#!/bin/sh

. /Applications/mappstack-7.1.13-0/scripts/setenv.sh

exec /Applications/mappstack-7.1.13-0/php/sbin/.php-fpm.bin -y /Applications/mappstack-7.1.13-0/php/etc/php-fpm.conf -p /Applications/mappstack-7.1.13-0/php/var/ -c /Applications/mappstack-7.1.13-0/php/etc/php.ini "$@"
